language: ruby
before_install:
 - git clone https://github.com/lightofanima/MU-Year-3-Group-Project.git
 - cd MU-Year-3-Group-Project/mu
 - rvm get head
 - rvm reinstall 1.9.3
before_script: "bundle exec rake db:drop db:create db:migrate"
rvm:
  - ruby-head
addons:
  postgresql: "9.3"
